from cnpj.tests.test_models.test_cpnj_cei import TestCnpjCei
from cnpj.tests.test_models.test_spreedsheets import TestSpreedsheets
from cnpj.tests.test_spreedsheets.test_processing_rfb_v1 import TestProcessingRfbV1