NATUREZA_JURIDICA = ((0, 'Empresário (Individual)'),
 (1, 'Sociedade Empresária Limitada'),
 (2, 'Produtor Rural (Pessoa Física)'),
 (3, 'Associação Privada'),
 (4, 'Candidato a Cargo Político Eletivo'),
 (5, 'Sociedade Unipessoal de Advocacia'),
 (6, 'Sociedade em Conta de Participação'),
 (7, 'Sociedade Anônima Fechada'),
 (8, 'Sociedade Simples Limitada'),
 (9, 'Cooperativa'),
 (10, 'Organização Religiosa'),
 (11, 'Sociedade Simples Pura'),
 (12,
  'Empresa Individual de Responsabilidade Limitada (de Natureza Empresária)'),
 (13, 'Sociedade Anônima Aberta'),
 (14, 'Condomínio Edilício'),
 (15, 'Sociedade de Economia Mista'),
 (16, 'Empresa Individual Imobiliária'),
 (17, 'Empresa Pública'),
 (18, 'Órgão Público do Poder Judiciário Estadual'),
 (19, 'Fundação Privada'),
 (20, 'Órgão Público do Poder Executivo Estadual ou do Distrito Federal'),
 (21, 'Sociedade Empresária em Nome Coletivo'),
 (22, 'Município'),
 (23, 'Serviço Notarial e Registral (Cartório)'),
 (24, 'Entidade Sindical'),
 (25, 'Fundo Público da Administração Direta Municipal'),
 (26, 'Estabelecimento, no Brasil, de Sociedade Estrangeira'),
 (27, 'Órgão de Direção Local de Partido Político'),
 (28, 'Autarquia Estadual ou do Distrito Federal'),
 (29, 'Consórcio de Sociedades'),
 (30, 'Serviço Social Autônomo'),
 (31, 'Órgão Público do Poder Executivo Municipal'),
 (32, 'Autarquia Federal'),
 (33, 'Sociedade Empresária em Comandita por Ações'),
 (34, 'Órgão Público do Poder Executivo Federal'),
 (35, 'Empresa Individual de Responsabilidade Limitada (de Natureza Simples)'),
 (36, 'Grupo de Sociedades'),
 (37, 'Autarquia Municipal'),
 (38, 'Fundação Pública de Direito Privado Municipal'),
 (39, 'Estabelecimento, no Brasil, de Fundação ou Associação Estrangeiras'),
 (40, 'Sociedade Mercantil de Capital e Indústria'),
 (41, 'Empresa Simples de Inovação'),
 (42, 'Organização Social (OS)'),
 (43, 'Órgão Público do Poder Legislativo Municipal'),
 (44, 'Entidade de Mediação e Arbitragem'),
 (45, 'Natureza Jurídica não informada'),
 (46, 'Consórcio Público de Direito Público (Associação Pública)'))