TYPES_STREET: tuple = (
    (0, "AVENIDA"),
    (1, "RUA"),
    (2, "ESTRADA"),
    (3, "VIELA"),
    (4, "RODOVIA"),
    (5, "ALAMEDA"),
    (6, "ENTRADA"),
    (7, "TRAVESSA"),
    (8, "PRACA"),
    (9, "ACESSO"),
    (10, "RESIDENCIAL"),
    (11, "ESTRADA MUNICIPAL"),
    (12, "ESTRADA PARTICULAR"),
    (13, ""),
    (14, "VEREDA"),
    (15, "VIA"),
    (16, "FAZENDA"),
    (17, "TREVO"),
    (18, "LARGO"),
    (19, "SETOR"),
    (20, "SITIO"),
    (21, "PASSARELA"),
    (22, "PRAÇA"),
    (23, "ACAMPAMENTO"),
    (24, "RUA PRINCIPAL"),
    (25, "LOTEAMENTO"),
    (26, "3O ALTO"),
    (27, "ANTIGA ESTRADA"),
    (28, "5A RUA"),
    (29, "ESTRADA VELHA"),
    (30, "RUA PARTICULAR"),
    (31, "AREA"),
    (32, "10A RUA"),
    (33, "CONDOMINIO"),
    (34, "1A RUA"),
    (35, "CHACARA"),
    (36, "OUTROS"),
    (37, "COLÔNIA"),
    (38, "RUA PROJETADA"),
    (39, "VILA"),
    (40, "1A AVENIDA"),
    (41, "DISTRITO"),
    (42, "CAMINHO"),
    (43, "ACESSO LOCAL"),
    (44, "RAMAL"),
    (45, "11A RUA"),
    (46, "1A TRAV. DA RODOVIA"),
    (47, "5A TRAVESSA"),
    (48, "9A RUA"),
    (49, "COND. RESIDENCIAL"),
    (50, "ES. PROJETADA"),
    (51, "6A AVENIDA"),
    (52, "ESTACAO"),
    (53, "SÍTIO"),
    (54, "CONJUNTO"),
    (55, "12A RUA"),
    (56, "3A RUA"),
    (57, "ESTRADA INTERMUNICIP"),
    (58, "ENTRADA PARTICULAR"),
    (59, "ÁREA"),
    (60, "EST. VIC. MUNICIPAL"),
    (61, "ESTRADA ANTIGA"),
    (62, "PATIO"),
    (63, "CONJUNTO HABITACIONA"),
)
