# Generated by Django 3.2.18 on 2023-02-22 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CnpjCei",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identification_number", models.CharField(max_length=14)),
                (
                    "type_identification",
                    models.IntegerField(choices=[(0, "CNPJ"), (1, "CEI")]),
                ),
                ("address", models.TextField()),
            ],
            options={
                "verbose_name": "CnpjCei",
                "verbose_name_plural": "CnpjCeis",
                "db_table": "",
                "managed": True,
            },
        ),
    ]
