# Generated by Django 3.2.18 on 2023-02-22 20:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cnpj", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cnpjcei",
            name="type_identification",
            field=models.IntegerField(choices=[(0, "CNPJ"), (1, "CEI"), (2, "CAEPF")]),
        ),
    ]
