# Generated by Django 3.2.18 on 2023-02-24 18:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cnpj', '0004_auto_20230223_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spreedsheets',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('spreedsheet', models.FileField(upload_to='')),
                ('processed', models.BooleanField()),
                ('version_used', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='cnpjcei',
            index=models.Index(fields=['identification_number'], name='cnpj_cnpjce_identif_27f497_idx'),
        ),
    ]
