# Generated by Django 3.2.18 on 2023-02-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnpj', '0005_auto_20230224_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spreedsheets',
            name='processed',
        ),
        migrations.AddField(
            model_name='spreedsheets',
            name='status',
            field=models.IntegerField(choices=[(0, 'Enviado'), (1, 'Processando'), (2, 'Erro'), (3, 'Processado com Sucesso')], null=True),
        ),
    ]
