# Generated by Django 3.2.18 on 2023-02-27 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnpj', '0006_auto_20230227_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='cnpjcei',
            name='social_capital',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
            preserve_default=False,
        ),
    ]
