# Generated by Django 3.2.18 on 2023-02-27 19:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cnpj', '0007_cnpjcei_social_capital'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cnpjcei',
            old_name='porte',
            new_name='company_size',
        ),
        migrations.RenameField(
            model_name='cnpjcei',
            old_name='natureza_juridica',
            new_name='legal_nature',
        ),
        migrations.RenameField(
            model_name='cnpjcei',
            old_name='motivo_situacao',
            new_name='reason_situation',
        ),
        migrations.RenameField(
            model_name='cnpjcei',
            old_name='situacao_cadastral',
            new_name='registration_status',
        ),
        migrations.AddField(
            model_name='cnpjcei',
            name='date_registration_status',
            field=models.DateField(null=True, verbose_name='Data do Status do Registro'),
        ),
        migrations.AddField(
            model_name='cnpjcei',
            name='phone2',
            field=models.CharField(max_length=50, null=True, verbose_name='Telefone 2'),
        ),
        migrations.AddField(
            model_name='cnpjcei',
            name='start_activities',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Inicio das Atividades'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cnpjcei',
            name='ccm',
            field=models.CharField(max_length=10, null=True, verbose_name='CCM'),
        ),
        migrations.AlterField(
            model_name='cnpjcei',
            name='complement_address',
            field=models.CharField(max_length=50, null=True, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='cnpjcei',
            name='fantasy_name',
            field=models.CharField(max_length=250, null=True, verbose_name='Nome Fantasia'),
        ),
        migrations.AlterField(
            model_name='spreedsheets',
            name='status',
            field=models.IntegerField(choices=[(0, 'Enviado'), (1, 'Processando'), (2, 'Erro'), (3, 'Processado com Sucesso')], default=0),
        ),
    ]
