# Generated by Django 3.2.18 on 2023-02-27 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnpj', '0008_auto_20230227_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cnpjcei',
            name='social_capital',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
