# Generated by Django 3.2.18 on 2023-02-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnpj', '0009_alter_cnpjcei_social_capital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cnpjcei',
            name='main_cnae',
            field=models.CharField(max_length=10, null=True, verbose_name='Principal CNAE'),
        ),
        migrations.AlterField(
            model_name='cnpjcei',
            name='neighborhood',
            field=models.CharField(max_length=50, null=True, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='cnpjcei',
            name='start_activities',
            field=models.DateField(null=True, verbose_name='Inicio das Atividades'),
        ),
        migrations.AlterField(
            model_name='cnpjcei',
            name='state',
            field=models.CharField(max_length=2, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='cnpjcei',
            name='street',
            field=models.CharField(max_length=250, null=True, verbose_name='Logradouro'),
        ),
        migrations.AlterField(
            model_name='cnpjcei',
            name='street_number',
            field=models.CharField(max_length=10, null=True, verbose_name='Numero'),
        ),
        migrations.AlterField(
            model_name='cnpjcei',
            name='zipcode',
            field=models.CharField(max_length=8, null=True, verbose_name='Código Postal'),
        ),
    ]
