# Generated by Django 3.2.18 on 2023-02-28 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnpj', '0012_auto_20230228_1652'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spreedsheets',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='spreedsheets',
            name='version_used',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
