# Generated by Django 3.2.18 on 2023-02-28 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnpj', '0013_auto_20230228_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spreedsheets',
            name='errors',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spreedsheets',
            name='version_used',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
