# Generated by Django 3.2.18 on 2023-03-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnpj', '0014_auto_20230228_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cnpjcei',
            name='complement_address',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Complemento'),
        ),
    ]
