# Generated by Django 3.2.18 on 2023-03-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnpj', '0015_alter_cnpjcei_complement_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='cnpjcei',
            name='ddd_phone',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='DDD Telefone'),
        ),
        migrations.AddField(
            model_name='cnpjcei',
            name='ddd_phone2',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='DDD Telefone 2'),
        ),
        migrations.AddField(
            model_name='cnpjcei',
            name='type_street',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
