# Generated by Django 3.2.18 on 2023-03-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnpj', '0016_auto_20230302_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cnpjcei',
            name='type_street',
            field=models.IntegerField(blank=True, choices=[(0, 'RUA'), (1, 'AVENIDA'), (2, 'ESTRADA'), (3, 'ALAMEDA')], null=True, verbose_name='Tipo de Logradouro'),
        ),
    ]
