# Generated by Django 3.2.18 on 2023-03-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spreadsheet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spreadsheet',
            name='version_used',
        ),
        migrations.AddField(
            model_name='spreadsheet',
            name='processor',
            field=models.CharField(choices=[('rfb_v1', 'rfb_v1')], default=1, max_length=250),
            preserve_default=False,
        ),
    ]
