# Generated by Django 3.2.18 on 2023-03-09 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spreadsheet', '0002_auto_20230306_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spreadsheet',
            name='processor',
            field=models.CharField(choices=[('rfb_v1', 'rfb_v1'), ('iss_v1', 'iss_v1')], max_length=250),
        ),
    ]
