# Generated by Django 3.2.18 on 2023-03-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tributos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iss',
            name='descricao_atividade',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='iss',
            name='base_calculo',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Valor ISS'),
        ),
        migrations.AlterField(
            model_name='iss',
            name='cod_atividade_cnae',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Codigo da Atividade'),
        ),
        migrations.AlterField(
            model_name='iss',
            name='iss_value',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Valor ISS'),
        ),
        migrations.AlterField(
            model_name='iss',
            name='tipo_servico',
            field=models.IntegerField(blank=True, choices=[(0, 'Instituição Financeira'), (1, 'Tomador'), (2, 'Prestador')], null=True, verbose_name='Tipo de Serviço'),
        ),
    ]
