# Generated by Django 3.2.18 on 2023-03-09 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tributos', '0002_auto_20230306_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iss',
            name='cnpj_cei',
        ),
        migrations.AddField(
            model_name='iss',
            name='identification_number',
            field=models.CharField(default='1233', max_length=14, verbose_name='Número de Identificação'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='iss',
            index=models.Index(fields=['identification_number', 'period', 'cod_atividade_cnae'], name='tributos_is_identif_b1b496_idx'),
        ),
    ]
