# Generated by Django 3.2.18 on 2023-03-09 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tributos', '0003_auto_20230309_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iss',
            name='cod_atividade_cnae',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Codigo da Atividade'),
        ),
    ]
